jaegertracing/jaeger-client-cpp

src/jaegertracing/Span.cpp
src/jaegertracing/Tracer.cpp
src/jaegertracing/TracerTest.cpp

Set default-constructed timestamp to current time in StartSpan

---

src/jaegertracing/Constants.h.in
src/jaegertracing/TracerTest.cpp

Add language prefix to Jaeger client version tag

---

src/jaegertracing/Config.h
src/jaegertracing/ConfigTest.cpp
src/jaegertracing/baggage/RestrictionsConfig.h
src/jaegertracing/propagation/HeadersConfig.h

Fix yaml-cpp issues (#36)

---

.clang-format
src/jaegertracing/reporters/CompositeReporter.h
src/jaegertracing/reporters/InMemoryReporter.h
src/jaegertracing/reporters/LoggingReporter.cpp
src/jaegertracing/reporters/LoggingReporter.h
src/jaegertracing/reporters/NullReporter.h
src/jaegertracing/reporters/RemoteReporter.cpp
src/jaegertracing/reporters/RemoteReporter.h
src/jaegertracing/reporters/Reporter.h

Guarantee a flush occurs on destruction of `RemoteReporter`. Add more `noexcept` specifiers for reporter methods.

Remote reporter flush fix

---

src/jaegertracing/LogRecord.h
src/jaegertracing/Span.cpp
src/jaegertracing/Tag.h
src/jaegertracing/TracerTest.cpp

Jaeger cpp-client was dropping logs included in a FinishSpanOptions
silently on the floor. Append them to the log buffer during FinishWithOptions instead.
Fixes #57
Signed-off-by: Craig Ringer <craig@2ndquadrant.com>

Record logs passed with Span::FinishWithOptions

---

src/jaegertracing/TracerFactoryTest.cpp

Signed-off-by: Ryan Burn <ryan.burn@gmail.com>
Sorry. Minor follow up to #64  to fix the test coverage. The TraceFactory tests was missing "#include "jaegertracing/Constants.h" which caused some of them not to run.

Fix dynamic loading test coverage.

---

src/jaegertracing/SpanContext.h

Add lock to SpanContext to protect baggage

---

CMakeLists.txt

Only test dynamic loading if building jaegertracing shared lib

---

CMakeLists.txt

The comon practice in cmake to allow to specify the libdir is
using GNUInstallDirs and the CMAKE_INSTALL_LIBDIR variable.
One of the usecases is setting /usr/lib64 as the destination dir
for libraries.

cmake: Use GNUInstallDirs instead of hardcoding lib destination

---

src/jaegertracing/Tracer.h
src/jaegertracing/TracerTest.cpp

tracer.Inject(SpanContext&, HTTPHeadersWriter&) was using the underlying
TextMapPropagator (instead of HTTPHeaderPropagator). This caused
injected baggage values not to be encoded.
Signed-off-by: Hugo Fernandes <hugof225@gmail.com>

Fix tracer.Inject(..., HTTPHeadersWriter&) (#107)

---

CONTRIBUTING.md
README.md

Instructions for building and running the example are added to README. Fixed formatting issue in CONTRIBUTING.md.
Relates #33, although these instructions aren't as in depth.
Signed-off-by: Isaac Brodsky <isaac@isaacbrodsky.com>

Add build instructions to README

---

CMakeLists.txt
cmake/CodeCoverage.cmake

Minor improvement. Will be useful for debugging race conditions by easily adding thread sanitizer flags, etc.

Improve C++ flag handling in CMake

---

src/jaegertracing/net/IPAddress.cpp

Fixes #129.
Signed-off-by: Tudor Bosman <tudor@rockset.com>
- #129 
- Just like the Jaeger Java client does, resolve the local hostname in order to determine the local IP address (to populate the "ip" tracer tag with).

localIP: try resolving local hostname first

---

src/jaegertracing/Span.cpp

`Span::isFinished()` returns true iff the span's duration is zero. So, if `steady_clock::now()` returns the same value at span creation as at `Finish()` (unlikely, but possible, especially in virtualized environments), the following scenario can happen:
- `Span::FinishWithOptions` sets `_duration` to zero
- and then calls `reportSpan`, which calls `RemoteReporter::report`
- which acquires the reporter mutex and
- adds the span to the reporter's `_queue`
Later:
- `RemoteReporter::sweepQueue` acquires the reporter mutex
- `RemoteReporter::sweepQueue` makes a copy of the span:
https://github.com/jaegertracing/jaeger-client-cpp/blob/7e9a135b362c47f7e4d42e0693b05b91a70e6888/src/jaegertracing/reporters/RemoteReporter.cpp#L95
- The span is serialized in `RemoteReporter::sendSpan`
- The span (the …

Fix deadlock if steady_clock::now() returns the same value twice

---

src/jaegertracing/SpanContext.h

This was method added to the opentracing API as a pure virtual method in <https://github.com/opentracing/opentracing-cpp/pull/56>. Without implementing this method, the jaeger client library cannot be used with recent (post-August-2018) versions of opentracing.

Implement SpanContext::Clone

---

src/jaegertracing/ConfigTest.cpp
src/jaegertracing/samplers/Config.h

- Resolves #144
- Instead of using 0 as the sentinel value for an unspecified sampler param, use another number that would be illegal instead. This allows param = 0 to be specified and respected by samplers.

Change sampler param sentinel value from YAML parser

---

src/jaegertracing/reporters/ReporterTest.cpp

- Avoid race conditions by relaxing test requirements.

Fix RemoteReporter test race condition

---

README.md

Resolves #122
Adds details on how to set the agent host:port and the collector URL in the README.

Add details on how to set agent & collector endpoints

---

src/jaegertracing/samplers/Config.h
src/jaegertracing/samplers/SamplerTest.cpp

Throw std::invalid_argument when the sampling rate is in the inclusive interval [0, 1] (#149)
Resolves #149
- When Probabilistic Sampler with an invalid rate is used (< 0 or > 1), a crash occurs when a span is created. 
- An std::invalid_argument exception is thrown when building a Probabilistic Sampler with an invalid rate.

Throw exception on invalid sampling rate

---

src/jaegertracing/LogRecord.cpp
src/jaegertracing/LogRecord.h
src/jaegertracing/Reference.cpp
src/jaegertracing/Reference.h
src/jaegertracing/ReferenceTest.cpp
src/jaegertracing/Span.cpp
src/jaegertracing/Span.h
src/jaegertracing/SpanTest.cpp
src/jaegertracing/Tag.cpp
src/jaegertracing/Tag.h
src/jaegertracing/TagTest.cpp
src/jaegertracing/UDPTransport.cpp
src/jaegertracing/reporters/Config.cpp
src/jaegertracing/reporters/Config.h
src/jaegertracing/samplers/AdaptiveSampler.cpp
src/jaegertracing/samplers/AdaptiveSampler.h
src/jaegertracing/samplers/RemotelyControlledSampler.cpp
src/jaegertracing/samplers/RemotelyControlledSampler.h
src/jaegertracing/samplers/SamplerTest.cpp

- Adresses https://github.com/jaegertracing/jaeger-client-cpp/issues/121
so that thrift is a private dependency of jaeger.
- Moved the minimal set of code from .h to .cpp to avoid thrift-gen headers to be exposed as part of the API.
Signed-off-by: Benoit De Backer <bdebacker@murex.com>

Remove Thrift headers from Jaeger public headers

---

CMakeLists.txt
README.md
src/jaegertracing/Config.cpp
src/jaegertracing/Config.h
src/jaegertracing/ConfigTest.cpp
src/jaegertracing/Tracer.cpp
src/jaegertracing/Tracer.h
src/jaegertracing/TracerFactory.cpp
src/jaegertracing/TracerTest.cpp
src/jaegertracing/net/IPAddress.h
src/jaegertracing/reporters/Config.cpp
src/jaegertracing/reporters/Config.h
src/jaegertracing/samplers/Config.cpp
src/jaegertracing/samplers/Config.h
src/jaegertracing/utils/EnvVariable.cpp
src/jaegertracing/utils/EnvVariable.h

Signed-off-by: FR-MUREX-COM\mchaikhadouaihy <mehrez.douaihy@gmail.com>
- Ability to fill a Tracer configuration from the environment variables
- Resolves #178
- Add fromEnv method to the Tracer Config class. The method will overwrite the configuration if the corresponding environment variable is set.
Supported properties
- Tracer
- JAEGER_SERVICE_NAME
- JAEGER_TAGS
- JAEGER_DISABLED
- Reporter
- JAEGER_AGENT_HOST
- JAEGER_AGENT_PORT
- JAEGER_ENDPOINT
- JAEGER_REPORTER_LOG_SPANS
- JAEGER_REPORTER_FLUSH_INTERVAL
- JAEGER_REPORTER_MAX_QUEUE_SIZE
- Sampler
- JAEGER_SAMPLER_TYPE
- JAEGER_SAMPLER_PARAM
- JAEGER_SAMPLER_MANAGER_HOST_PORT

Support Tracer tags and  configuration via environment variables

---

src/jaegertracing/Tracer.cpp
src/jaegertracing/TracerTest.cpp

resolves #136 
If the trace was started with a debugID, adding jaeger-debug-id
as tag ensures that the trace will be sampled in the "debug" mode.
Additionally, the root span will have this ID as a searchable tag.

Add jaeger-debug-id as a tag

---

README.md
src/jaegertracing/ConfigTest.cpp
src/jaegertracing/samplers/Config.cpp
src/jaegertracing/samplers/Config.h
src/jaegertracing/samplers/SamplerTest.cpp

fix conversion to double of JAEGER_SAMPLER_PARAM
rename env var JAEGER_SAMPLER_MANAGER_HOST_PORT to JAEGER_SAMPLER_SERVER_URL
properly load JAEGER_SAMPLER_SERVER_URL
Signed-off-by: CI-Bot for Emmanuel Courreges <emmanuel.courreges@orange.com>

Fix loading of sampling endpoint address from JAEGER_SAMPLING_ENDPOINT environment variable

---

.travis.yml
CMakeLists.txt
cmake/Hunter/config.cmake
src/jaegertracing/Span.cpp
src/jaegertracing/Span.h
src/jaegertracing/SpanContext.h
src/jaegertracing/TracerTest.cpp

- This solves the request #189 
- Update the version of OpenTracing to 1.6.0
- GTest version was fixed to 1.8.0-hunter-p11 because the later versions seem to have a problem with the rpath making the unit test fail because the binaries are unable to locate the gtest libraries. This issue will be followed separately to avoid blocking this request.
This will also solve another problem reported by @Alek86 in #208. This was due to a bug in OpenTracing compile flags that was fixed with the latest release.

Update OpenTracing to 1.6.0

---

src/jaegertracing/ConfigTest.cpp
src/jaegertracing/DynamicLoad.cpp
src/jaegertracing/TracerFactory.cpp
src/jaegertracing/TracerFactory.h
src/jaegertracing/TracerFactoryTest.cpp
src/jaegertracing/testutils/EnvVariable.cpp
src/jaegertracing/testutils/EnvVariable.h
src/jaegertracing/utils/EnvVariable.h

Support using the environment variables added in https://github.com/jaegertracing/jaeger-client-cpp/pull/181 when using the plugin. E.g. as part of https://github.com/opentracing-contrib/nginx-opentracing/
The plugin entry point now tries to parse the yaml file and loads environment variables if they are defined. Once all configuration methods performed, validate that the service name is not empty.

Support plugin configuration via environment variables

---

CHANGELOG.md
CMakeLists.txt

Prepare release 0.6.0

---

src/jaegertracing/SpanContext.h
src/jaegertracing/SpanContextTest.cpp
src/jaegertracing/TraceID.h
src/jaegertracing/TraceIDTest.cpp

- Implements jaegertracing/jaeger#1657

Do not strip leading zeros from trace IDs and span IDs

---

src/jaegertracing/Config.cpp
src/jaegertracing/Config.h
src/jaegertracing/ConfigTest.cpp
src/jaegertracing/Tracer.h
src/jaegertracing/TracerTest.cpp
src/jaegertracing/testutils/TracerUtil.cpp

- Using 128 Bit trace ids increases interoperability with W3C Trace Context (and other Jaeger clients)
- Resolves #254
- added a flag if 128 bit trace ids should be generated

Support configuration for generating 128 bit trace ids

---

src/jaegertracing/Config.h
src/jaegertracing/ConfigTest.cpp

At the moment setting the tracer tags is only possible via an environment variable. It should also be possible to set them via the configuration (file).
* I enhanced the parse the parse method to read a new configuration key for the tracer tags

Added support for setting tracer tags via the configuration
