jaegertracing/jaeger-client-cpp

CHANGELOG.md
=> Preparing for release 0.1.0

CHANGELOG.md, CMakeLists.txt
=> Back to development

CMakeLists.txt, src/jaegertracing/net/IPAddress.cpp
=> Fix bug in localIP and revert change in TR1 tuple definition

CHANGELOG.md
=> Preparing for release 0.2.0

CMakeLists.txt
=> Fix CMAKE_INCLUDE_CURRENT_DIR typo

CMakeLists.txt, cmake/HunterGate.cmake
=> Update Hunter to get newest OpenTracing API

scripts/build.sh
=> Add missing exit to build script

CMakeLists.txt, src/jaegertracing/DynamicallyLoadTracerTest.cpp
=> Fix dynamic load test to include macros in Constants header

CHANGELOG.md
=> Preparing for release 0.3.0

RELEASE.md
=> Fix instructions for release

.dockerignore, .travis.yml, CMakeLists.txt, crossdock/Dockerfile, crossdock/docker-compose.yml, scripts/build.sh, scripts/upload-coverage.sh
=> Add more compilers to Travis

CMakeLists.txt
=> Update Hunter to get newest OpenTracing C++ v1.4.0

CHANGELOG.md
=> Preparing for release 0.4.0

CMakeLists.txt, src/jaegertracing/DynamicLoadTest.cpp
=> Fix dynamic load test

CMakeLists.txt
=> Fix name of OpenTracing package in CMake config

CHANGELOG.md, CMakeLists.txt
=> Preparing for release 0.4.1

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Signed-off-by: Prakriti prakritibansal98@gmail.com
refs jaegertracing/jaeger#785
=> Adding new issue and PR template 

.ycm_extra_conf.py
License issue #116 
Self-explanatory
=> Use Apache 2 license for YCM config

CHANGELOG.md, CMakeLists.txt
=> Preparing for release 0.4.2

CHANGELOG.md
Signed-off-by: Mehrez DOUAIHY <mehrez.douaihy@gmail.com>
- Prepare for release 0.4.3
- Prepare the changelog
=> Preparing release 0.5.0

src/jaegertracing/ThriftSender.cpp, src/jaegertracing/ThriftSender.h
Replaces #180 
Previous approach allocates several max size buffer everytime we
want to calculate the size of the serialized thrift type. This changes
to reuse only 1 buffer per sender. As sender is single-threaded this should be
safe.
I manually modified the build script and example app to include sanitizer stats and producing span in a loop https://gist.github.com/dqminh/b64099d775d72e584a141a0d20c38a00. After compling you can run it with `ASAN_OPTIONS=verbosity=1:atexit=1:print_stats=1 ./app ../examples/config.yml 10`
Before:
```
AddressSanitizer exit stats:
Stats: 1M malloced (0M for red zones) by 1140 calls
Stats: 0M realloced by 0 calls
Stats: 1M freed by 1094 calls
Stats: 0M really freed by 0 calls
Stats: 5M (5M-0M) mmaped; 87 maps, 0 unmaps
mallocs by size class: 2:80; 3:261; …
```
=> reuse TMemoryBuffer when calculating size of ThriftType

.github/workflows/macos.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml, README.md
Implemented a workflow for building the CMake on Ubuntu, macOS, and Windows, and badge to display their status on README.
A successful run can be seen [here](https://github.com/leozz37/jaeger-client-cpp/actions).
=> Implemented GitHub Actions workflow for builds on Ubuntu, MacOS and Windows

.github/workflows/macos.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml, src/jaegertracing/ThriftSenderTest.cpp, src/jaegertracing/TracerTest.cpp, src/jaegertracing/testutils/TracerUtil.cpp, src/jaegertracing/testutils/TracerUtil.h
- Currently GitHub Actions only build the library but do not execute the tests
- Added a test step to the workflows
- Fixed the tests
=> GitHub Actions should execute tests

.github/workflows/ubuntu.yml
The Ubuntu workflow fails
Build everything with gcc/g++ 7
=> Fixed Ubuntu workflow
